import Header from "../components/Header";
import SummaryChart from "@/components/SummaryChart"
import Summary from "@/components/Summary"
import Items from "@/components/Items"
import SummaryProvider from "@/components/SummaryProvider"
// import Linechart from "@/components/Linechart"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  // const session = useSession()


  return (
    <SummaryProvider>

      <Header />


      <main className="max-w-7xl mx-auto my-8">
        <div className="grid grid-cols-3 gap-4">
          <div className="col-span-1">
            <h2 className="text-xl font-semibold mb-4">Products</h2>
             <Items />
          </div>
          <Summary />
        </div>
        <SummaryChart />
      </main>

      <footer className="bg-gray-800 text-white py-4">
        <div className="container mx-auto text-center">
          &copy; Hackathon 2024 ReviewFluence.
        </div>
      </footer>
    </SummaryProvider>
  );
}
